apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryu-test
  description: The place to be, for great artists
  labels:
    app_owner: ryu
  annotations:
    example.com/service-discovery: artistweb
  tags:
    - java
  links:
    - url: https://google.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: public-websites

