apiVersion: v1
kind: Service
metadata:
  name: user-sample-service
  labels:
    app: user-sample-service
    tier: api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: user-sample-service
